In [1]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [16]:
a = np.array([1,2,3, 4.5])
print(a, type(a))
print(a.dtype)
print(a.shape)
print('size', a.size)
print('itemsize', a.itemsize)
print('', a.ndim)

[1.  2.  3.  4.5] <class 'numpy.ndarray'>
float64
(4,)
size 4
itemsize 8
 1


In [12]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [28]:
a = np.array(range(16))
print(a, a.dtype)

print()
a = np.array([1,2,3, 40000000000000000], ndmin = 2)
print(a, a.dtype)
print('itemsize', a.itemsize, a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] int32

[[                1                 2                 3 40000000000000000]] int64
itemsize 8 (1, 4)


In [47]:
a = np.arange(10,19)
print(a)

a1 = a.reshape(3,3)

print(a)
print(a1)

a = np.arange(10,19,2)
print(a, a.mean(), a.min(), a.max(), a.sum())

a = np.array( [ [1,2],  [3,4] ])
print(a)

[10 11 12 13 14 15 16 17 18]
[10 11 12 13 14 15 16 17 18]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[10 12 14 16 18] 14.0 10 18 70
[[1 2]
 [3 4]]


In [59]:
a = np.arange(0,24, dtype = 'i4').reshape(4,6)
print(a, a.dtype)

print(a.min(), a.max())
print(a.min(axis = 0), a.max(axis = 0))
print(a.min(axis = 1), a.max(axis = 1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] int32
0 23
[0 1 2 3 4 5] [18 19 20 21 22 23]
[ 0  6 12 18] [ 5 11 17 23]


In [63]:
a= np.random.randint(10,20,100).reshape(10,10)
print(a)

[[15 14 16 10 19 15 15 10 12 14]
 [15 18 13 15 18 13 15 10 12 10]
 [11 13 15 15 14 18 18 17 13 18]
 [19 10 10 16 14 13 16 10 11 11]
 [14 11 17 14 15 16 14 14 13 10]
 [14 12 17 10 10 11 18 16 15 14]
 [13 15 19 13 11 11 13 19 14 16]
 [16 10 15 12 17 19 12 11 18 10]
 [13 17 14 13 11 13 10 14 12 12]
 [18 17 19 10 10 10 15 19 11 18]]


In [78]:
a = np.arange(10,100, 10)
print(a)
r = a.resize(2,4)
print(a, r)
a.resize(20)
print(a)

a = np.zeros(10, dtype = 'int8')
print(a)

[10 20 30 40 50 60 70 80 90]
[[10 20 30 40]
 [50 60 70 80]] None
[10 20 30 40 50 60 70 80  0  0  0  0  0  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0]


### indexing and slicing

In [90]:
a = np.arange(12).reshape(4,3)
print(a)
print()

print(a [1])
print(a [0,2])
print()
print(a [1:3])
print(a [1:3, 1: ])

print(np.linspace(10,20,20, dtype = 'int8'))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[3 4 5]
2

[[3 4 5]
 [6 7 8]]
[[4 5]
 [7 8]]
[10 10 11 11 12 12 13 13 14 14 15 15 16 16 17 17 18 18 19 20]


In [2]:
a = np.arange(12).reshape(4,3)
print(a)
print()

print(a [ (0,2), ])
print()
print(a [ : ,(0,2) ])
print()
print(a [ (0,2), (1,2)])
print()
print(a [ (True, False, False, True), ])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[0 1 2]
 [6 7 8]]

[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]

[1 8]

[[ 0  1  2]
 [ 9 10 11]]


In [115]:
a = np.arange(10,20)
a2 = np.arange(20,10,-1)
print(a, a2)
print(a * 2)
print(a * a2)

print()
res = (a % 2 == 0)
print(res)
print(a[res])

print()
res = (a %3 == 0) | (a%5 == 0)
print(res)
print(a[res])

print()
res = (a %3 == 0) & (a%5 == 0)
print(res)
print(a[res])

[10 11 12 13 14 15 16 17 18 19] [20 19 18 17 16 15 14 13 12 11]
[20 22 24 26 28 30 32 34 36 38]
[200 209 216 221 224 225 224 221 216 209]

[ True False  True False  True False  True False  True False]
[10 12 14 16 18]

[ True False  True False False  True False False  True False]
[10 12 15 18]

[False False False False False  True False False False False]
[15]


In [124]:
print(np.nan < 0)
print(np.nan > 0)
print(np.nan == 0)
print(np.nan == np.nan)

a = np.array( [10,10, np.nan])
print( a, a.sum(), a.mean())

False
False
False
False
[10. 10. nan] nan nan


In [135]:
a = np.arange(10,20, dtype = np.float64)
a[3] = np.nan

print(a)
res = (a %3 == 0) | (a%5 == 0)
print(res)
print(res.any())
print(res.all())
print(np.isnan( a ))
print(np.isnan( a ).sum())

[10. 11. 12. nan 14. 15. 16. 17. 18. 19.]
[ True False  True False False  True False False  True False]
True
False
[False False False  True False False False False False False]
1


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in remainder
  """


In [139]:
a = np.arange(10,20, dtype = np.float64)
a[3] = np.nan

print(a)
res = (a %3 == 0) | (a%5 == 0)
print(res)
print(np.where(res))

[10. 11. 12. nan 14. 15. 16. 17. 18. 19.]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in remainder
  """


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [143]:
print(1 or 2) # logical or
#print( 1 || 2)
print( 1 | 2) # bitwise or
print( bin(1) , bin (2))

1
3
0b1 0b10
